apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1 # Có thể tăng số lượng replicas để tăng khả năng chịu lỗi và tải
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: docker_presentation:0.0.1
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/docker_presentation # Sử dụng tên Service của MySQL
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: Manh99123 # Nên sử dụng Secret để bảo mật mật khẩu
            - name: TZ
              value: Asia/Ho_Chi_Minh
          ports:
            - containerPort: 8080