#apiVersion: v1
#kind: Service
#metadata:
#  name: backend-service
#spec:
#  selector:
#    app: backend
#  ports:
#    - protocol: TCP
#      port: 8080 # Cổng mà Service lắng nghe
#      targetPort: 8080 # Cổng của container
#  type: NodePort # Hoặc LoadBalancer nếu bạn chạy trên cloud và muốn expose ra ngoài

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer # Thay đổi thành LoadBalancer