apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Đảm bảo dung lượng này nhỏ hơn hoặc bằng dung lượng của PV (nếu có PV tĩnh)