#apiVersion: v1
#kind: Service
#metadata:
#  name: mysql-service
#spec:
#  selector:
#    app: mysql
#  ports:
#    - protocol: TCP
#      port: 3306 # Cổng mà Service lắng nghe
#      targetPort: 3306 # Cổng của container
#  type: ClusterIP # ClusterIP là loại mặc định, chỉ có thể truy cập bên trong cluster

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer # Thay đổi thành LoadBalancer