apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-deployment
spec:
  replicas: 1 # Có thể tăng số lượng replicas để tăng khả năng chịu lỗi và tải
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway:0.0.2
          env:
            - name: INFO_SERVICE
              value: http://info-service-service:8081
            - name: TZ
              value: Asia/Ho_Chi_Minh
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer