apiVersion: apps/v1
kind: Deployment
metadata:
  name: info-service-deployment
  labels:
    app: info-service-deployment
spec:
  replicas: 2 # Có thể tăng số lượng replicas để tăng khả năng chịu lỗi và tải
  selector:
    matchLabels:
      app: info-service
  template:
    metadata:
      labels:
        app: info-service
    spec:
      containers:
        - name: info-service
          image: info-service:0.0.2
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/info_service
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: Manh99123
            - name: TZ
              value: Asia/Ho_Chi_Minh
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: info-service-service
spec:
  selector:
    app: info-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer